name = "BoseHubbardDiagonalize"
uuid = "89f0727c-bc31-11e8-1ce6-853ab2505967"
authors = ["Roger Melko <rgmelko@uwaterloo.ca>", "Dmitri Iouchtchenko <diouchtc@uwaterloo.ca>"]
version = "0.1.0"

[deps]
JeszenszkiBasis = "4eec09b6-37c8-513a-a01b-84ce271f0312"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.3"
